name: release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'tag and release to create'
        # Input has to be provided for the workflow to run
        required: true
env:
  GITHUB_ENV: ".env"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@0caeaed6fd66a828038c2da3c0f662a42862658f
        with:
          go-version: ^1.17
      - name: Check out code into the Go module directory
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: master
      - name: Login to dockerhub to push the image
        run: echo "${{ secrets.DockerHubToken }}" | docker login --username ${DOCKER_USER} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DockerHubUser }}
      - name: Publish Docker Image
        env:
          VERSION: ${{ github.event.inputs.tag }}
        run: make ci publish
      - name: run make bump-version
        run: make bump-version
        env:
          NEW_VERSION: ${{ github.event.inputs.tag }}
      - name: commit manifests
        uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b
        with:
          message: "create release manifests for ${{ github.event.inputs.tag }}"
          add: "releases/ VERSION CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # target commit should be the commit with the new release manifest, not the commit when workflow was triggered
      - name: find target commit to tag
        run: |
          sha=$(git rev-parse HEAD)
          echo "TARGET_SHA=$sha" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ env.TARGET_SHA }}
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          body: See the [CHANGELOG](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/${{ github.event.inputs.tag }}/CHANGELOG.md) for details.
