name: ci
on:
  pull_request:
  push:
    branches: [ master ]
env:
  GOFLAGS: "-mod=vendor"
  GITHUB_ENV: ".env"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@0caeaed6fd66a828038c2da3c0f662a42862658f
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 1

      - name: Verify docker image builds
        run: make build

      - name: Run test command
        run: make ci

  release-dev-image:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Install go
        uses: actions/setup-go@0caeaed6fd66a828038c2da3c0f662a42862658f
        with:
          go-version: ^1.17

      - name: checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 1

      - name: Login to dockerhub to push the image
        run: echo "${{ secrets.DockerHubToken }}" | docker login --username ${DOCKER_USER} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DockerHubUser }}
      - name: build and push new CCM dev image
        run: |
          VERSION=dev make publish
